### PR TITLE
Add back-to-back-stem-and-leaf plots

### PR DESCRIPTION
**Pull request by tobyWorland**
Fulfills issue #1

### CODE REVIEW

**Comment by Symbolics** [comment]
Looks good. Two things:

1. Will you please make `back-to-back` a keyword option in `stem-and-leaf`. This way the usage would be something like: `(stem-and-leaf foo :back-to-back t)`.  Same for `split-stems` (if you do that one), `(stem-and-leaf x :split-stems t)`.  The keyword defaults for those should be `nil`
2. Squash all commits with a single commit message like "implement back to back stem plots".  See [how to write a good commit message](https://cbea.ms/git-commit/) for some guidelines.

**Comment by Symbolics** [comment]
I've just edited my comment. I had split brain syndrome :-) because initially we were discussing `split-stems` and this PR implements `back-to-back`.  We really shouldn't mix `&optional` and `&keys` parameters, so `back-to-back` does need to be separate since it takes both `x` and `y`.  `split-stems` we can signal with a keyword to `stem-and-leaf`.

Thanks for the contribution!

**Comment by tobyWorland** [comment]
Thanks for the review!

> initially we were discussing split-stems and this PR implements back-to-back.

Ah, I think you're confusing me for @jg20019. I have not participated in the discussion for the other issue.

> Squash all commits with a single commit message like "implement back to back stem plots".

Done

> Will you please make split-stems a keyword option ...

Done, plus I added it to the docstring.

**Comment by Symbolics** [comment]
Well done, thanks!

**Pull request merged**
